### ISSUE TITLE
Need provider resources for Identity Source Sequence

### ISSUE THREAD

**Issue by grg1bbs** [CiscoDevNet/terraform-provider-ise#22]
Provider is missing a resource for creating an Identity Source Sequence, a config item commonly used in Authentication Policies. Both resource and data source objects should be available for create and get operations based on the APIs documented here:
https://developer.cisco.com/docs/identity-services-engine/latest/#!idstoresequence

**Comment by danischm** [comment]
https://github.com/CiscoDevNet/terraform-provider-ise/commit/e86a92d922f0e5de8dc27eba6dc9d7f516b78a49

**Comment by danischm** [comment]
Added in v0.1.9 .
